vim.wo.number = true -- Show line numbers (default: false)
vim.o.clipboard = 'unnamedplus' -- Use system clipboard (default: '')
vim.o.wrap = false -- Do not wrap lines (default: true)
vim.o.linebreak = true -- Wrap lines at convenient points (default: false)
vim.o.mouse = 'a' -- Enable mouse support (default: '')
vim.o.autoindent = true -- Enable auto-indent (default: false)
vim.o.ignorecase = true -- Ignore case when searching (default: false)
vim.o.smartcase = true -- Override 'ignorecase' if search has uppercase characters (default: false)
vim.o.shiftwidth = 4 -- Number of spaces to use for auto-indent (default: 8)
vim.o.tabstop = 4 -- Number of spaces that a <Tab> in the file counts for (default: 8)
vim.o.softtabstop = 4 -- Number of spaces that a <Tab> counts for while editing (default: 0)
vim.o.expandtab = false -- Use tabs instead of spaces for indentation (default: false)
vim.o.scrolloff = 6 -- Number of lines to keep above/below the cursor (default: 0)
vim.o.sidescrolloff = 8 -- Number of columns to keep to the left/right of the cursor (default: 0)
vim.o.cursorline = true -- Highlight the current line (default: true)
vim.o.splitbelow = true -- Split windows below the current window (default: false)
vim.o.splitright = true -- Split windows to the right of the current window (default: false)
vim.o.hlsearch = true -- Highlight search results (default: true)
vim.o.showmode = false -- Do not show mode (default: true)
vim.opt.termguicolors = true -- Use true colors (default: false)
vim.o.numberwidth = 4 -- Width of the number column (default: 4)
vim.o.swapfile = false -- Do not create swap files (default: true)
vim.o.smartindent = true -- Enable smart indent (default: false)
vim.o.showtabline = 2 -- Always show the tabline (default: 1)
vim.o.backspace = 'indent,eol,start' -- Allow backspacing over everything in insert mode (default: 'indent,eol,start')
vim.o.pumheight = 10 -- Maximum number of items in the popup menu (default: 15)
vim.o.conceallevel = 0 -- Show concealed text normally (default: 1)
vim.wo.signcolumn = 'yes' -- Always show the sign column (default: 'auto')
vim.o.fileencoding = 'utf-8' -- Set file encoding to UTF-8 (default: 'utf-8')
vim.o.cmdheight = 1 -- Height of the command-line (default: 1)
vim.o.breakindent = true -- Enable break indent (default: false)
vim.o.updatetime = 250 -- Time in ms to wait for CursorHold events (default: 4000)
vim.o.timeoutlen = 300 -- Time in ms to wait for a mapped sequence to complete (default: 1000)
vim.o.backup = false -- Do not create backup files (default: false)
vim.o.writebackup = false -- Do not create backup files before overwriting (default: false)
vim.o.undofile = true -- Enable persistent undo (default: false)
vim.o.completeopt = 'menuone,noselect' -- Completion options (default: 'menu,preview')
vim.opt.shortmess:append 'c' -- Do not give ins-completion-menu messages (default: '')
vim.opt.iskeyword:append '-' -- Treat dash-separated words as a word (default: '@,48-57,_,192-255')
vim.opt.formatoptions:remove{'c', 'r', 'o'} -- Do not auto-wrap comments (default: 'tcq')
vim.opt.runtimepath:remove '/usr/share/vim/vimfiles' -- Remove system runtime path (default: '/usr/share/vim/vimfiles')
